    name: Build and Test on Push

    on:
      push:
        branches:
          - '**'  # Trigger on any branch

    jobs:
      build:
        runs-on: ubuntu-latest

        container:
          image: fedora:latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Install Python and Dependencies on Fedora
            run: |
              dnf update -y
              dnf install -y python3 python3-pip python3-virtualenv python3-tkinter
              curl -sSL https://install.python-poetry.org | python3 -
              echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

          - name: Install dependencies
            run: |
              ~/.local/bin/poetry install

          - name: Run package script
            run: |
              chmod +x ./package.sh
              ./package.sh

          - name: Archive build result
            uses: actions/upload-artifact@v2
            with:
              name: build-${{ github.ref }}
              path: ./dist/64All