- name: sm64ex_alo
  url: "https://github.com/AloUltraExt/sm64ex-alo.git"
  dependencies:
    - "build-essential"
    - "libglew-dev"
    - "libsdl2-dev"
  info:
    description: |
      sm64ex_alo is a fork of sm64pc/sm64ex that incorporates several enhancements and new features. It reintroduces support for N64 building, which was removed in sm64ex, and is based on a more recent update compared to the older sm64ex version. Notable additions include Puppycam 2, as opposed to Puppycam 1 in sm64ex, quality of life fixes and features with QOL_FIXES=1 and QOL_FEATURES=1, and mouse support for desktop targets via SDL1/SDL2 with MOUSE_ACTIONS=1 (DirectX Mouse support is not yet implemented). It also offers a simple debug options menu (EXT_DEBUG_MENU=1) and integrates Kaze more objects patch with PORT_MOP_OBJS=1.
    image: "sm64exalo.png"
  options:
    QOL_FIXES:
      recommended: 1
      description: 'Quality of life fixes'
      default: 0
      values: [ 0, 1 ]
    QOL_FEATURES:
      recommended: 1
      description: 'Quality of life features'
      default: 0
      values: [ 0, 1 ]
    MOUSE_ACTIONS:
      description: 'Mouse support for desktop targets'
      default: 0
      values: [ 0, 1 ]
    EXT_DEBUG_MENU:
      description: 'Simple debug options menu'
      default: 0
      values: [ 0, 1 ]
    TARGET_BITS:
      recommended: 64
      description: |
        TARGET_BITS=n appends some compiler flags for an n-bit build. If the value is empty, 
        the option does nothing, assuming your native toolchain will set everything up by itself. 
        Use this only if you are having trouble otherwise.
      default: 32
      values: [ 32, 64 ]
      advanced: true
    WINDOWS_CONSOLE:
      default: 0
      values: [ 0, 1 ]
      description: |
        Append -mconsole to Windows CFLAGS, making a console window appear while the game is 
        running. Can be useful for debugging purposes.
      advanced: true
    DEBUG:
      default: 0
      values: [ 0, 1 ]
      description: 'Build with debug symbols and default optimization level. Otherwise build with -O2.'
      advanced: true
    RENDER_API:
      default: "GL"
      values: [ "GL", "GL_LEGACY", "D3D11", "D3D12" ]
      description: |
        Select rendering backend to use. GL corresponds to OpenGL 2.1 (gfx_opengl.c), 
        GL_LEGACY corresponds to OpenGL 1.3 (gfx_opengl_legacy.c). Direct3D backends will 
        also force WINDOW_API to DXGI.
      advanced: true
    AUDIO_API:
      default: "SDL2"
      values: [ "SDL1", "SDL2" ]
      description: 'Select audio backend. Keep in mind that you CANNOT mix SDL1 and SDL2.'
      advanced: true
    EXTERNAL_DATA:
      recommended: 1
      default: 0
      values: [ 0, 1 ]
      description: |
        Load textures and soundbanks from external files. Allows you to use texture packs. 
        The default data is copied to a res folder next to the produced executable.
      advanced: true
    TEXTSAVES:
      default: 0
      values: [ 0, 1 ]
      description: 'Use INI-based save format instead of binary EEPROM dumps. Experimental.'
      advanced: true
    BETTERCAMERA:
      recommended: 1
      default: 1
      values: [ 0, 1 ]
      description: 'Enable better camera.'
    NODRAWINGDISTANCE:
      recommended: 1
      default: 1
      values: [ 0, 1 ]
      description: 'Enable no drawing distance limit.'
    TEXTURE_FIX:
      recommended: 1
      default: 1
      values: [ 0, 1 ]
      description: 'Enable various texture-related bugfixes (e.g. fixes the smoke texture).'
    EXT_OPTIONS_MENU:
      recommended: 1
      default: 1
      values: [ 0, 1 ]
      description: |
        Enable Options menu. Accessed from the Pause menu by pressing R.
    DISCORDRPC:
      default: 0
      values: [ 0, 1 ]
      description: 'Enable Discord Rich Presence support. Only works on x86_64.'